### ISSUE TITLE
boost anaconda (linux)

### ISSUE THREAD

**Issue by tohnperfect** [classner/fertilized-forests#29]
I am using anaconda as my python package manager. Please note that, I am very new to linux and cmake.
I have tried to build your codes by 
-first modify  CMakeList.txt at line 155 and 159 to point to ../anaconda/include/boost and run cmake ..
-then I run cmake --build . and i get this error message.

>.. /fertilized-forests-master/build_support/external/Boost.NumPy/libs/numpy/src/dtype.cpp:9:36: fatal error: boost/numpy/internal.hpp: No such file or directory
 #include <boost/numpy/internal.hpp>
                                    ^
compilation terminated.
make[2]: *** [build_support/external/Boost.NumPy/libs/numpy/src/CMakeFiles/boost_numpy.dir/dtype.cpp.o] Error 1
make[1]: *** [build_support/external/Boost.NumPy/libs/numpy/src/CMakeFiles/boost_numpy.dir/all] Error 2
make: *** [all] Error 2

any suggestion how could I config the CMakeList.txt to be able to build the codes and use the python interface.

**Comment by classner** [comment]
Hi!

You should not have to adjust the CMakeLists.txt, but only configure variables for CMake. You can call cmake repeatedly and pass it -DVARNAME=VALUE arguments to change their values. They will be stored in your build folder in a file named CMakeCache.txt (you can open it with your favorite editor and have a look at what CMake stored there).

Did you already change the CMakeLists.txt? Because the error you get indicates a missing Boost Numpy installation, which should be not possible. Boost numpy ships with the library (it is located in `build_support/external/Boost.NumPy`) and is compiled statically into the library.

Best,
Christoph

**Comment by tohnperfect** [comment]
Hello Christoph,

I deleted the fertilized folder and do cmake from the fresh copy again without editing CMakeList.txt and passing any arguments. Surprisingly I successfully installed the package.

Thank you very much,
Tohn

**Comment by classner** [comment]
That is great to hear!
