### ISSUE TITLE
NoCopyPatchSampleManager : ValueError: Object at sequence position 105 can not be converted to target type N7ndarray5ArrayIKhLi3ELi3EEE!

### ISSUE THREAD

**Issue by tohnperfect** [classner/fertilized-forests#31]
Hi,

I have tried to run python example hough_train.py by just passing RGB numpy array instead of the specified feature in the example and I got the following error. 

> Traceback (most recent call last):
  File "hough_train.py", line 112, in <module>
    False)
  File "../../build/bindings/python/fertilized/__init__.py", line 4116, in NoCopyPatchSampleManager
    patches_luc
ValueError: Object at sequence position 105 can not be converted to target type N7ndarray5ArrayIKhLi3ELi3EEE!

My goal is to use hough forest to train my own dataset with different feature than those specified in the original paper by Juergen Gall and Victor Lempitsky. Could I pass numpy array type image to the HoughTree as well as NoCopyPatchSampleManager?
Sorry for bothering you with many issues lately.

Tonh

**Comment by tohnperfect** [comment]
When I pass np.ascontiguousarray(image) instead, I got the following error.

> Traceback (most recent call last):
  File "hough_train.py", line 112, in <module>
    False)
  File "../../build/bindings/python/fertilized/__init__.py", line 4116, in NoCopyPatchSampleManager
    patches_luc
RuntimeError: Invalid patch location for patch 0: position 266, 162 (x, y) for image size 3, 315 (width, height) for patch size 16, 16 (width, height).

which looks like the shape of an image in the function is incorrect the original image.shape =  (232, 315, 3)

**Comment by classner** [comment]
So the first error occurs, because the array is not of the correct type. In the type information is included:
* numpy array dtype (probably uint8 in your case),
* contiguity of the array.

The second point is important as well and means, that the array must be C_CONTIGUOUS in memory. You can check that by using the `.flags` property of the array.

I consciously chose not to do automatic casting in these cases, because the library is intended for high performance computing, i.e., maybe working with very large datasets. In that case, the automatic 'cast' of the numpy array would result in a maybe fatal copy of the array for the OS, because the memory consumption exceeds sane boundaries. So while having to deal with these annoying things once, they lead to having a faster piece of software.

In your second attempt, you sorted that out by using the `ascontiguousarray` method. It seems, though, you are passing your images in with dimension ordering (#Channels, Height, Width) as they are usually prepared for deep learning ;). For this library, they must be in standard format as you would read them in with, e.g., OpenCV, so (Height, Width, #Channels).

**Comment by tohnperfect** [comment]
I passed the image  with shape  (Height, Width, #Channels) which is originally from np.array(Image.open()) method in your example (hough_train.py).

**Comment by classner** [comment]
Sorry, I was wrong here: the order *is* (#Channels, Height, Width) (also see [here](http://www.multimedia-computing.de/fertilized/api_doc/1.02/html/classfertilized_1_1_no_copy_patch_sample_manager.html) in the docs). The method in the example has this automatically, because it uses the output of `extract_hough_forest_features`, which is already in the correct format.

**Comment by tohnperfect** [comment]
Thanks. I managed to get it working by reshape the numpy.array to have shape = (#Channels, Height, Width)

**Comment by classner** [comment]
Just be careful to __not__ use the `reshape` function for your array if it is (Height, Width, #Channels) before. This would result in the values having wrong indices! You must use `transpose((2, 0, 1))` instead, which you probably did.

I just wanted to make sure, because otherwise you will get absolutely meaningless classifiers...

**Comment by priyankavokuda** [comment]
Hi,

I am trying to run python example hough_train.py using deep features instead of features given in the example.
The deep features are of datatype float32.

I get following error:
` NoCopyPatchSampleManager
    patches_luc
ValueError: Object at sequence position 0 can not be converted to target type N7ndarray5ArrayIKhLi3ELi3EEE!
` 
Example of what I am trying to do: 
`feat_images = [np.random.randint(0, 500, size=(128, im.shape[0], im.shape[1])).astype(np.float) for im in cvimages]`

I also observed that possible instantiations for NoCopyPatchSampleManager are:
   * - uint8_t; int16_t
   * - uint8_t; uint

Is there a way to use features of datatype float32?
