### ISSUE TITLE
Link Error

### ISSUE THREAD

**Issue by kensho-** [classner/fertilized-forests#33]
I got this error when I tried to save StandardHoughTree with input_dtype == float, feature_dtype == int16_t, annotation_dtype == int16_t.
```
17	error LNK2001: ""__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fertilized::serialize<class fertilized::Forest<float,short,short,struct std::pair<float,class std::shared_ptr<class std::vector<short,class std::allocator<short> > > >,class std::vector<struct std::pair<float,class std::shared_ptr<class std::vector<short,class std::allocator<short> > > >,class std::allocator<struct std::pair<float,class std::shared_ptr<class std::vector<short,class std::allocator<short> > > > > > > >(class fertilized::Forest<float,short,short,struct std::pair<float,class std::shared_ptr<class std::vector<short,class std::allocator<short> > > >,class std::vector<struct std::pair<float,class std::shared_ptr<class std::vector<short,class std::allocator<short> > > >,class std::allocator<struct std::pair<float,class std::shared_ptr<class std::vector<short,class std::allocator<short> > > > > > > const *,bool const &)" (__imp_??$serialize@V?$Forest@MFFU?$pair@MV?$shared_ptr@V?$vector@FV?$allocator@F@std@@@std@@@std@@@std@@V?$vector@U?$pair@MV?$shared_ptr@V?$vector@FV?$allocator@F@std@@@std@@@std@@@std@@V?$allocator@U?$pair@MV?$shared_ptr@V?$vector@FV?$allocator@F@std@@@std@@@std@@@std@@@2@@2@@fertilized@@@fertilized@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBV?$Forest@MFFU?$pair@MV?$shared_ptr@V?$vector@FV?$allocator@F@std@@@std@@@std@@@std@@V?$vector@U?$pair@MV?$shared_ptr@V?$vector@FV?$allocator@F@std@@@std@@@std@@@std@@V?$allocator@U?$pair@MV?$shared_ptr@V?$vector@FV?$allocator@F@std@@@std@@@std@@@std@@@2@@2@@0@AEB_N@Z)"  is unsolved.	C:\Users\Hara\Documents\Visual Studio 2013\Projects\FertilizedTest\FertilizedTest\main.obj	FertilizedTest
```

If the input_dype is uint8_t, there is no error.
I think this error is according to boost::serialization.

Here is my environment.
Windows 7
Visual Studio 2013
boost: 1.58.0
OpenCV: 2.4.11
Eigen: 3.2.8
C++

I want to change the features by extract_hough_forest_features to the others.
Could you tell me how to solve the problem?

**Comment by classner** [comment]
Hi Kensho!

## The problem

Yes, the serialization with Boost Python must know about all types that can be serialized in advance, also regarding templatization. The appropriate serialization routines will then be built and registered. For trees, there is the type

```
uint8_t; int16_t; int16_t; std::pair<float, std::shared_ptr<std::vector<int16_t>>>; std::vector<std::pair<float, std::shared_ptr<std::vector<int16_t>>>>
```

registered, representing a hough forest with the corresponding structures. To have other Hough forests, you must add their type, rebuild the library and can then store it. (Using it is no problem, since no boost serialization is involved).

This is the most serious one of some of the pitfalls of using Boost Serialization, but at the time I preferred it over alternatives like Protobuf, because they also come with their problems.

## How you can solve it

There is an easy way to solve this:

* Open your `tree.h` file and add your hough forest type after line 52 in the commentary section of the tree (if you want to do this for the forest as well, add a corresponding section in the comments of `forest.h`. Go to the [developer's guide](http://www.multimedia-computing.de/fertilized/pages/developers-guide.html) and downoad the `fertilized-devtools` project as described.
* `cd` there and run `python generate.py` to generate your updated library bindings.
* Rebuild and you're done. Serialization should work as expected.

Maybe do it for the tree first, check it works, and do it then for the forest as well.

**Comment by kensho-** [comment]
Thank you for your reply.
I tried to add the following line after line 52 in ```tree.h```.
```
   * - float; float; int16_t; std::pair<float, std::shared_ptr<std::vector<int16_t>>>; std::vector<std::pair<float, std::shared_ptr<std::vector<int16_t>>>>
```
Then, I run ```python generate.py```.
But I got the following error.
```
Tree using ILeafManager, and has instantiation f_f_int16_hp_vhp, which is not present for parent!
Tree using UnchangedDataProvider, and has instantiation f_f_int16_hp_vhp, which is not present for parent!
Tree using ISurfaceCalculator, and has instantiation f_f_int16_hp_vhp, which is not present for parent!
Tree using IDecider, and has instantiation f_f_int16_hp_vhp, which is not present for parent!
Tree using ThresholdDecider, and has instantiation f_f_int16_hp_vhp, which is not present for parent!
Traceback (most recent call last):
  File "generate.py", line 194, in <module>
    parse_using_instantiations(using_relations)
  File "generate.py", line 193, in parse_using_instantiations
    raise Exception("Errors validating relations: %s" % str(exc))
Exception: Errors validating relations: True
```

If I removed the added line, no error occured.

What is the problem?

**Comment by classner** [comment]
The generator runs consistency checks: for every object instantiation, it checks that the objects used by that object are also available in the according datatypes (to make it easy with an example, the `Tree` uses an `ILeafManager`, so for every possible instantiation of the `Tree`, there must be an appropriate instantiation of the `ILeafManager` available).

The dependencies listed give you all first order dependencies for which this is true. So you can now open, e.g., `ILeafManager.h` and add also a line with the appropriate types to its comment (the f_f_int16_hp_vhp is just a short representation for `float`, `float`, `int16`, `hough_predictions`, `vector of hough predcitions` to make the template parameters more readable). There are hardly any more follow-up dependencies, but the ones that come to my mind immediately, are the HoughLeafManager, the ThresholdDecider and the Difference- or DirectPatchDifferenceSurfaceCalculator.

That's quite some steps, but they should be easy to take and are, unfortunately, unavoidable.

**Comment by kensho-** [comment]
Thank you!
I solved this problem!

**Comment by classner** [comment]
Good to hear! :)
