### ISSUE TITLE
hough_train.py does not work

### ISSUE THREAD

**Issue by kensho-** [classner/fertilized-forests#34]
Hi, Christoph.

I face another problem.
I tried to execute the hough forests example ```hough_train.py```.
But it does not work.
In ```hough_train.py```, the following code exists.
```
feat_images = [soil.extract_hough_forest_features(im, full=(n_feature_channels==32)) for im in cvimages]
```
```python.exe``` crashed when execute above code.

I used the following environment.
Windows 7
Visual Studio 2013
boost: 1.58.0
OpenCV: 2.4.11
Eigen: 3.2.8
C++

When I used ```extract_hough_forest_features``` function in C++, no error occurred.

Could you tell me how to solve the problem?

**Comment by classner** [comment]
I will have a look at this probably on Tuesday. How is the soil object configured? Did you change the feature extraction code? And which images do you use?

**Comment by kensho-** [comment]
Thank you for your reply.
I just execute ```hough_train.py```.
So, the soil object type is ```fertilized.Soil('uint8', 'int16', 'int16', fertilized.Result_Types.hough_map)```, 
and the images are Weizmann Horse Dataset.
I did not change the feature extraction code.

**Comment by classner** [comment]
Hi Kensho,

so I just checked on a Windows machine: the examples including `hought_train.py` are working flawlessly on Windows with Boost 1.58, OpenCV2.4.11, Python 2.7.5 and VS 2013. This is the configuration with which I built the downloadable, pre-compiled fertilized-forests v1.0.2 for the Website.

Can you confirm that the downloaded version works for you? I am afraid, due to time-constraints, I am not able to provide detailed build support for every possible version. If you want to track down the issue, create a debug build (-DCMAKE_BUILD_TYPE=Debug), let the program run, output its process ID and wait for input, attach with the Visual Studio debugger to it and set a breakpoint at the feature extraction method, and let it continue. Then, you should be able to find exactly the place where something is going wrong...

Let me know if this helps and about your findings!
Christoph

**Comment by kensho-** [comment]
I tried to use the pre-complied version, and it works perfectly.
My purpose is achieved.
I mainly use C++, and I just want to confirm the result of ```predict_image``` function in python version.
I implemented c++ version of ```hough_train.py``` and ```hough_detect.py```.
But the result of ```predict_image``` function was strange.
So I wanted to confirm the right result.
The results in c++ and python are different.
So my implementation is wrong.
I wil try to confirm my implementation.

Thank you.

**Comment by classner** [comment]
Ok, I see. So just to check: the predict_image function needs a feature image, not the original image. The dimensions must be n_features X height X width. I recall you wanted to change the feature datatype. The feature extraction function uses internally bit tricks to be efficient, so it will only work with uint8 images. You can then convert them to float if your forest works like that.

And, of course, you should train and test the hough forest on the same features extracted by the same method.

Does any of that sound relevant? Just trying to give helpful hints...

**Comment by kensho-** [comment]
Thank you for your hints.
But I found that my problems is just using wrong parameters...
I set ```min_samples_per_split = 2000```...
It was impossible to train tree using the parameter...
I fixed ```min_samples_per_split = 20```, then the result of ```predict_image``` become correct.

Thank you again for your helpful reply.

**Comment by classner** [comment]
I am glad to hear that! Good luck with the hough forests, they're a powerful tool! :)
