### ISSUE TITLE
ForestFromTrees: "Tried to reset a node's decision parameters."

### ISSUE THREAD

**Issue by christian-rauch** [classner/fertilized-forests#36]
Hello,

I try to add trees manually to a forest by using `Soil`'s `ForestFromTrees` method: [main.cpp.txt](https://github.com/classner/fertilized-forests/files/630807/main.cpp.txt)

Mainly, I am extending the `custom.cpp` example file by creating a vector of trees:
```decltype(soil.tree_vec_t()) trees;```
and adding the same tree configuration multiple times:
```
for(uint i(0); i<2; i++) {
    trees.push_back(decltype(soil.tree_vec_t())::value_type(
                        new decltype(soil.tree_vec_t())::value_type::element_type(20, 1, 2, tClassifier, leafMgr)
                        ));
}
```
and finally create the forest from this vector:
```auto forest = soil.ForestFromTrees(trees, training);```

When I call the fit method, I get the exception:
```
terminate called after throwing an instance of 'fertilized::Fertilized_Exception'
  what():  Tried to reset a node's decision parameters.
```

From the definition of the `ForestFromTrees` method in `soil.h`, it should use the Forest constructor
`fertilized::Forest::Forest(trees, training)` that combines **untrained** trees.

Why is the fit method trying to reset the decision parameters if I provide untrained trees?

**Comment by classner** [comment]
Hi!

Your idea is perfectly valid, the problem is located in your example code at a different position: you only create one set of classifiers / leaf managers, etc. for both trees. Then the root node for the decider is created for the first tree and when trying to create it for the second, the exception is thrown. I will create a test for this to prevent this from happening in the future (things could go horribly wrong if you do parallel training)...

Pulling the lines for the creation of the objects into the loop, everything works for me.

Best,
Christoph

**Comment by christian-rauch** [comment]
Hello,
I see now that I am actually passing only the pointer to both trees instead of individual instances of classifier and leaf-manager.
After generating one classifier and one leaf-manager per tree, I obtain the same results: [tree_manual_add.cpp.txt](https://github.com/classner/fertilized-forests/files/633629/tree_manual_add.cpp.txt)
Thanks.
