### ISSUE TITLE
Hough forest does not support 1D annotations

### ISSUE THREAD

**Issue by tomhaeck** [classner/fertilized-forests#40]
Hey,

I am trying to build a Hough forest with 1D annotations (i.e. 1D offset vectors).  The library is doing everything to prevent this from happening.  Either errors are thrown by the NoCopyPatchSampleManager, or the covariance matrices of the vectors are positive semidefinite in the VarianceClassificationThresholdOptimizer, etc.  

Has anyone tried this before?

Tom

**Comment by classner** [comment]
Hi Tom!

Was in vacation last week, sorry for the delay. I didn't try it, it's certainly not a direct use case of classic Hough Forests: the dimensionality of the offset vectors in general should be the same as for the input modality, so in the case of images 2D. Could you briefly describe what you are trying to do, slightly more high level?

In any case, doing this will require changes in several places; I'll be happy to assist if required. I assumes you adjusted the patch sample manager. The threshold optimizer assumes 2D offset vectors for regression, but that as well should be easily adjustable. If this assumption is violated, the classification values are included into the regression, which explains the semidefinite matrices.

Best,
Christoph

**Comment by tomhaeck** [comment]
Hi Christoph,

Apologies for somehow missing your answer.

I 'solved' the problem a while ago by forcing the 1D  regression problem to be 2D.  It was certainly not the nicest of all solutions, but it was quick and it worked;-).

To be frank, I generally find it difficult to exploit the 'modularity' of  the library.  Everything works fine if one formulates the problem as a typical classification problem, a typical regression problem or a typical 2D hough forest problem.  Every small deviation from these patterns causes me a lot of trouble.

For instance,

two weeks ago I was trying to classify 2D images into 8 classes (all images of different dimensions).  A patch-based approach seemed the best way to go, i.e. every patch within every images votes for a category.  All votes for all patches in an image are accumulated to obtain the final classification of the image.  All building blocks for this are present in the library:

- NoCopyPatchSampleManager
- ClassificationLeafManager
- ThresholdDecider:
-- VolumeFeatureSelectionProvider
-- DirectPatchDifferenceSurfCalculator
-- RandomizedClassificationThresholdOptimizer

It should be relatively easy to combine these blocks, but it is not.  The NoCopyPatchSampleManager is not compatible, the serialization fails for customized trees, ...  The code for my custom classification tree is attached.  The data to fit this tree to, is provided by a NoCopyPatchSampleManager and a SubsamplingDataProvider (just as in the standard Hough tree case).  

```
  template<typename input_dtype, typename feature_dtype, typename annotation_dtype>
  std::shared_ptr<fertilized::Tree<input_dtype, feature_dtype, uint,
	  std::vector<float>, std::vector<float>> > construct_custom_labeling_tree(
	  const std::vector<size_t> &patch_dimensions,
	  const uint &n_classes,
	  const size_t &n_thresholds_per_split,
	  const size_t &n_splits_per_node,
	  uint max_depth,
	  const std::vector<uint> &min_sample_counts,
	  const uint &random_seed,
	  const float &min_gain_threshold,
	  const bool &patch_annot_luc = false,
	  const bool &allow_redraw = true,
	  const uint &num_threads = 1,
	  const float &entropy_p1 = 2.f) {

	
	  size_t patch_x = patch_dimensions[0];
	  size_t patch_y = patch_dimensions[1];
	  size_t patch_z = patch_dimensions[2];
	
	  uint min_samples_at_leaf = min_sample_counts[0];
	  uint min_samples_at_node = min_sample_counts[1];

	  std::shared_ptr<IEntropyFunction<float>> entropy;
	  entropy = std::make_shared<InducedEntropy<float>>(entropy_p1);

	  auto gainc = std::make_shared<EntropyGain<float>>(entropy);

	  auto thresh_opt = std::shared_ptr<RandomizedClassificationThresholdOptimizer<input_dtype, feature_dtype, uint>>(
			  new RandomizedClassificationThresholdOptimizer<input_dtype, feature_dtype, uint>(
			 n_thresholds_per_split, 
			 n_classes, gainc, min_gain_threshold, 
			 1, random_seed));

	  size_t real_selections_to_generate = n_splits_per_node;
	  if (allow_redraw)
		  real_selections_to_generate = 3 * n_splits_per_node;
	  auto feat_sel = std::shared_ptr<VolumeFeatureSelectionProvider>(
		  new VolumeFeatureSelectionProvider(2, patch_x, patch_y, patch_z,
		  real_selections_to_generate, random_seed));

	  auto surf_calc = std::shared_ptr<DirectPatchDifferenceSurfCalculator<input_dtype, feature_dtype, uint>>(
		  new DirectPatchDifferenceSurfCalculator<input_dtype, feature_dtype, uint>(patch_x, patch_y, patch_z,
		  patch_annot_luc));

	  size_t n_valids_to_use = 0;
	  if (allow_redraw)
		  n_valids_to_use = n_splits_per_node;
	  auto weak_classifier = std::shared_ptr<ThresholdDecider<input_dtype, feature_dtype, annotation_dtype>>(
		  new ThresholdDecider<input_dtype, feature_dtype, annotation_dtype>(feat_sel, surf_calc,
		  thresh_opt, n_valids_to_use, num_threads, false, 0.05f, 0, false));

	  auto leaf_man = std::shared_ptr<ClassificationLeafManager<input_dtype, uint>>(
		  new ClassificationLeafManager<input_dtype, uint>(n_classes));

	  return std::make_shared<Tree<input_dtype, feature_dtype, uint, std::vector<float>, std::vector<float >> >(
		  max_depth, min_samples_at_leaf, min_samples_at_node, weak_classifier, leaf_man);
  };
```

**Comment by classner** [comment]
Hi Tom!

I'm glad to hear that you solved the 2D/1D problem! It's really not the cleanest, but certainly a quick and elegant solution.

I agree with your criticism. It's not even usually the problem that the library objects could not live up to the idea of modularity, but that the general library structure is making this way too complicated (I'll comment on your particular case below). The templates are useful, but very, very unhandy and especially the serialization is causing trouble in many cases. To account for these problems and still allow a dynamic development process while keeping the library and all interfaces up to date, I started the project for automatic code generation to pick up changes in the library files and update all the rest (https://github.com/classner/fertilized-devtools). Boost serialization has cost me countless hours with debugging. :-/  As a whole, I think the implemented objects of the library are mostly fine, but the way they're tied together is clunky and makes development unnecessary hard.

This year in March I decided to take a step back and rethink the core design of the library. With the new tools from C++14 (and potentially C++17) I hoped to get rid of many of the problems and I think succeeded for most of my aims. I called the project `forpy` and you can find it here:
https://github.com/classner/forpy

It has no dependencies to external libraries, no code generator is necessary, etc. The objects are a lot simpler and cleaner due to the use of `mu::variant` (a C++14 implementation of `std::variant` coming in C++17) (some core objects are still using templates and pragmas for types, but will also be replaced with `variant`). I improved the core regression and classification objects still quite a bit in efficiency, etc. For serialization I use http://uscilab.github.io/cereal/, which is a *lot* easier to use and debug. However, the project is still incomplete (the Hough forest objects are missing, so far I only implemented trees but not forests since that was not necessary for development and benchmarking). Due to the use of PIMPL without type templates, compilation is very fast. Last but not least, the Python bindings and library are extremely efficient with pybind11 instead of Boost Python (and boost is not a dependency anymore). This comes much closer to what I had imagined this library to be, but still requires a bit of work and some time.

As to your concrete problem: the NoCopyPatchSampleManager is one of the trickies objects in the library, since it only stores each image once and provides a function to map a point within the patch to the image coordinates. Where did you have the compatibility problems? Why did you implement the customized tree? The reason that the custom tree can't be serialized is with Boost Serialization. It must be registered with it. You need to provide a serialization function with

    void serialize(Archive & ar, const uint file_version) {
      ar & boost::serialization::base_object<Tree<...>>(*this);
      //...
    }

Then you should increase the library version in the CMakeLists.txt file and run the code generation tool from https://github.com/classner/fertilized-devtools and recompile. Then serialization should work as expected.

**Comment by tomhaeck** [comment]
Hey Christoph,

Thanks for the quick response on a Monday morning;-)

> It's not even usually the problem that the library objects could not live up to the idea of modularity.

I think the modularity suffers a bit from the natural trade off between object generality and speed performance.  Very specialized classes work fast but are difficult to deploy in other ways as for their originally intended purpose. I think this trade off is a design choice for every library and is related to the main audience of the library?  

The NoCopyPactchSampleManager is an excellent example of performance vs. customization?  

> I called the project forpy and you can find it here: https://github.com/classner/forpy.  It has no dependencies to external libraries, no code generator is necessary, etc.

I very much like the sound of the 'no dependencies'!  Also, I am by no means a C++ expert, but the more a C++ library approaches the 'header-only' concept, the better I like it.

> As to your concrete problem:

The serialization is a problem.  I am missing an instantiation from the Forest class: `uint8_t; int16_t; uint; std::vector<float>; std::vector<float>`.  At the moment, I am circumventing this problem by serializing the individual trees (Tree class has this particular instantiation).  How do I add this particular instantiation to the Forest class?

> Why did you implement the customized tree? 

I want to classify image patches in 8 classes.  It is kind of a Hough tree, but without the regression part of the classical Hough tree and with >2 classes as is assumed in the Fertilized Forest implementation.  I am slowly getting there, but it proved to be more difficult than I had anticipated.  When I have more concrete questions, apart from the instantiation question, I will get back to you.

Thanks for the support,

Tom

**Comment by tomhaeck** [comment]
I have added the specific Forest instantiation that was mentioned in the previous email using the fertilized dev-tools.  Works well.

**Comment by classner** [comment]
That's very good to hear! Did this solve your current problem? In that case I'd close this issue...
